export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  PHONE_ALREADY_REGISTERED: 'PHONE_ALREADY_REGISTERED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSE: 'REFRESH_TOKEN_REUSE',
  PROPERTY_NOT_FOUND: 'PROPERTY_NOT_FOUND',
  PROPERTY_NOT_APPROVED: 'PROPERTY_NOT_APPROVED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  DATES_UNAVAILABLE: 'DATES_UNAVAILABLE',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  GUEST_CAPACITY_EXCEEDED: 'GUEST_CAPACITY_EXCEEDED',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_NOT_COMPLETABLE: 'BOOKING_NOT_COMPLETABLE',
  COUPON_INVALID: 'COUPON_INVALID',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_LIMIT_REACHED: 'COUPON_LIMIT_REACHED',
  COUPON_MIN_AMOUNT: 'COUPON_MIN_AMOUNT',
  REVIEW_NOT_ALLOWED: 'REVIEW_NOT_ALLOWED',
  PAYMENT_NOT_VERIFIED: 'PAYMENT_NOT_VERIFIED',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
  REFUND_NOT_ELIGIBLE: 'REFUND_NOT_ELIGIBLE',
  INVALID_COORDINATES: 'INVALID_COORDINATES',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  OTP_LOCKED: 'OTP_LOCKED',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  SMS_PROVIDER_ERROR: 'SMS_PROVIDER_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export interface ApiErrorBody {
  success: false;
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
}

export interface ApiSuccessBody<T> {
  success: true;
  data: T;
}
